# Generated by Django 4.2.16 on 2025-01-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikels'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Auteur', 'verbose_name_plural': 'Auteurs'},
        ),
    ]
