# Generated by Django 4.2.16 on 2025-01-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaties', '0002_alter_article_options_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(default='media/publicaties/', upload_to='publicaties/'),
        ),
    ]
