# Generated by Django 4.2.16 on 2025-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaties', '0003_article_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pdf',
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
